### ISSUE TITLE
Performance on classification datasets

### ISSUE THREAD

**Issue by Svithjod** [xmed-lab/CLIP_Surgery#13]
Hi, thanks for your great work! I just wonder have you tried CLIP Surgery on traditional classification datasets like ImageNet and Cifar?

**Comment by Eli-YiLi** [comment]
Single label like imagenet is not influenced, because architecture surgery is designed for explainability task, and feature surgery compute the redundant feature as a common bias for each class. Thus, giving a same bias doesn’t change the rank and accuracy, instead it influences scores across images and benefits mAP for multilable.

**Comment by GewelsJI** [comment]
Hi, @Eli-YiLi 

Thanks for your nice work. I have two questions here.

1. How to understand 'common bias' that you mentioned above?
2. Why replacing 'QKV' with 'VVV' can solve the problem of Opposite Visualization problem in your manuscript?

**Comment by Eli-YiLi** [comment]
1. common bias means the redundant feature is the same for all classes and don't change the rank.
2. QKV self-attention learns wrong relation, which swaps foreground tokens to backgrounds and vice versa as Fig. 4. In contrary, VV self-attention computes self-attention for the feature from parameter v itself. It forces the highest similarity locating at the token itself, and similar tokens are highlighted too. But this rule is not applicable to QKV self-attention, since QK may change the original feature to another feature leading to wrong relation.
