### ISSUE TITLE
About input sentence for SAM 

### ISSUE THREAD

**Issue by lwpyh** [xmed-lab/CLIP_Surgery#14]
Hi there

Thanks for this good work!

I am trying to explore input a sentence to get some satisfied SAM results with CLIp surgery, could you please provide some suggestions on it?

Best.

**Comment by Eli-YiLi** [comment]
According to the multimodal visualization, only partial object and keywords are activiated. Thus, if you want to capture multiple regions, it's suggested to combine keywords as the demo. If your need is the whole sentence, please rm the redundant feature of empty string, while the results may not be as your wish, because of the nature of CLIP.
