### ISSUE TITLE
mIoU evaluation for  open-vocabulary segmentation

### ISSUE THREAD

**Issue by WalBouss** [xmed-lab/CLIP_Surgery#17]
Thanks for your work and for sharing the code!

It is, however unclear to me how the **mIoU** was computed for the open-vocabulary segmentation tasks. 
In the paper (sec.5.1.3 page 10), you mention that:

> "Specifically, the mIoU is also used to measure the visualization quality. While each positive label is evaluated independently with a grid search threshold to identify the foreground."

I have several questions:

1. For each image, do you only evaluate the mIoU of the classes present in the image? _i.e.,_ if there is only a "cat" and "dog" in the image, you only compute the mIoU for those 2 classes?
2. It appears to me that you define one similarity threshold for every class. Hence,  how do you find the optimal threshold?
3. Is the computed threshold the same across the dataset, or do you compute it for each image?

Thanks,

**Comment by Eli-YiLi** [comment]
For open-vocabulary segmentation, the mIoU is evaluated as common semantic segmentation, just applying argmax to get labels without any threshold.

The threshold is needed in explainability task, because many tasks (e.g. image manipulation) use the heatmap for open world without fixed label set. Thus, we need foregrounds without argmax for each class and evaluate via binary mIoU (for question1).

For the threshold, all methods use the grid search strategy to obtain it. Specifically, firstly applying min-max norm to 0-1 and search with GT using step 0.01 to get the best threshold. This search is applied to each image and class independently (question 2 & 3).

Besides, mSC requires no threshold. And another non-searched threshold is also applicable, namely auto threshold via opencv: cv2.threshold(similarity_map, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU). While grid search is more accurate than auto-threshold to evaluate the quality of heatmap, so we use it.

**Comment by WalBouss** [comment]
Thank you very much for your prompt answer!

When you say that for open-vocabulary segmentation, you just apply _"argmax to get labels without any threshold"_, does it means that you also consider the "background" as being a class? 
Or do you compute the IoU only with the foreground classes? 

I'm asking because if you consider "background" as a class, its text embedding will not be very informative. Indeed, what goes into the background highly depends on what the dataset creators decided to annotate.

**Comment by Eli-YiLi** [comment]
I am sorry to confuse you.
In detail, I computed the IoU of each foreground, and mean every positive classes to get the mIoU.
