### ISSUE TITLE
How can I make similarity_map_to_points select multiple objects!

### ISSUE THREAD

**Issue by isabellemehiganKPMG** [xmed-lab/CLIP_Surgery#18]
First of all great work and thank you for sharing!

I have a question that I am in the process of figuring out but I thought I would post it here incase it was useful. I was able to get everything working quite successfully but I ran into a case I had a problem with. As you can see below I have a photo with two birds, through clip.get_similarity_map I was able to select the two birds

![Screenshot 2023-06-01 at 14 53 18](https://github.com/xmed-lab/CLIP_Surgery/assets/105419172/798ac7eb-6544-40c4-b43e-e2877f772049)

After when I want to implement clip.similarity_map_to_points to infer for SAM, it only seems to provide me with one bird

![Screenshot 2023-06-01 at 14 56 05](https://github.com/xmed-lab/CLIP_Surgery/assets/105419172/56e8ea8b-aab8-4b53-bf02-93b008638d29)

As you can guess in the title, I think this is a limitation of similarity_map_to_points method, but I am not sure. Would you be able to provide some clarity on similarity_map_to_points  method any/or maybe suggest why this is happening. 

Again, great work and thank you for posting!

**Comment by Eli-YiLi** [comment]
Thanks for your interest. 

This problem is caused by this function: def similarity_map_to_points(sm, shape, t=0.8, down_sample=2):
The function determines the points number: num = min((sm >= t).sum(), sm.shape[0] // 2), and this problem occurs when few points are higher than it.
My suggestion is to use auto threshold to chose threshold points as: t = cv2.threshold(similarity_map, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU). It may helps.
