### ISSUE TITLE
question for equation 8

### ISSUE THREAD

**Issue by zyhhh123** [xmed-lab/CLIP_Surgery#19]
Thanks for your excellent work, but I can't understand that the redundant features Fr can be obtained with equation 8. Can you help me with this question?

**Comment by Eli-YiLi** [comment]
Hi,

You can refer to the code:
![image](https://github.com/xmed-lab/CLIP_Surgery/assets/49093246/4e89d284-874c-4064-8290-55a7f5f578a5)

We used the class weight w for the multiplied feature Fm. Note, element-wise production with sum is equal to matrix production to calculate the cos similarity. So, Fr is also a kind of weighted mean similarity map. And it's similar to the map from empty string, since most labels are not appeared in one image.
